### ISSUE TITLE
lib/zstd_static and programs/fileio.h have different line ending

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/zstd#12]
It seems that these files in all branches have CRLF line endings instead of LF.

**Comment by Cyan4973** [comment]
Mmmh, this is possible, since the development is done in both Windows and Linux/BSD configurations.
However, that's exactly the reason why there is a .gitattributes file : it's supposed to check for line ending on all files, and even correct them on the fly.

Now, I wonder if a .gitattributes scope is limited to its current directory. Maybe sub-directories remain unaffected...

**Comment by t-mat** [comment]
As far as I know, usual glob filenames in `.gitattributes` are recognized as file mask for all subdirectories as you expected.

Perhaps, "Refreshing a repository after changing line endings" section in GitHub's guide "[Dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/)" helps you. Since these files have not changed from initial commit, just "refreshing" may resolve this problem.

**Comment by Cyan4973** [comment]
OK, thanks
The procedure is clear to follow.
Line endings are now fixed in both branches.
