### ISSUE TITLE
v0.6.0 Streaming API

### ISSUE THREAD

**Issue by luben** [Cyan4973/zstd#160]
I know it is work in progress but just to point out that the streaming API (from zstd_static.h) is incompatible with the results of the CLI zstd program.

- when compressing it creates result that is 8 bytes smaller then the CLI
- when decompressing a file compressed by the CLI util I get "Src size incorrect" on the first ZSTD_decompressContinue with the size returned by the first invocation of ZSTD_nextSrcSizeToDecompress.

The streaming API is compatible in itself though - it roundtrips the compression/decompression.

**Comment by Cyan4973** [comment]
Thanks for the notification.
Indeed, `dev060` branch was not yet fully stabilized, but we are getting close to this point.
We'll look into this issue too.

**Comment by Cyan4973** [comment]
The 8 bytes of difference come from one version storing the frame content length, and the other version not.

Presumably, the streaming version does not store this information, because it doesn't know it.
The cli version can know it if the source is provided as a file : `zstd filename` .
But if it is provided as pipe data, it will not : `cat filename | zstd -c > filename.zst`

I presume the problem come from the presence of the frame content field, making the header larger.
There is indeed a difficulty now, because the size of the frame header is basically variable.

It can be made to work, since `zbuff` is just using this API successfully, but maybe it's too complex or tortured.
I will have a closer look into it.

**Comment by luben** [comment]
I will take a look how is done in zbuff.c or may be switch directly to it.

**Comment by luben** [comment]
I made it work but it is sub-optimal IMHO, here is how it works in my case:

1. Without size:

- ZSTD_createDCtx + ZSTD_decompressBegin
- do the ZSTD_decodeParams, reading the first 5 bytes (the frame header)
- allocate the buffers (using sizes in the params)
- call ZSTD_decompressContinue on the frame header
- continue with alternating ZSTD_nextSrcSizeToDecompress and ZSTD_decompressContinue

2. With size:

- ZSTD_createDCtx + ZSTD_decompressBegin
- do the ZSTD_decodeParams, reading the first 13 bytes (the frame header 5 + 8)
- allocate the buffers (using sizes in the params)
- call ZSTD_decompressContinue on the first 5 bytes of the frame header
- copy the next 8 bytes of the frame header in the inputBuffer
- call ZSTD_decompressContinue on it
- continue with alternating ZSTD_nextSrcSizeToDecompress and ZSTD_decompressContinue

I think the main difficulty comes from ZSTD_decodeParams assuming that it can peek into the next X bytes without consuming them and so all the trouble with copying back and forth the already read data.

Another question, how can I tell if the original size is encoded and be able to read it?

Regards,
luben

**Comment by luben** [comment]
One option to make it work in the both cases the same is if the ZSTD_decompressContinue can consume the whole 13 byte frame header in one go if it is given to it (currently it fails with "src size incorrect" error) and then continue expecting the 3 byte header.

**Comment by luben** [comment]
small PR with my proposal coming soon

**Comment by luben** [comment]
Scrap the proposed PR, it adds more complexity. It can be done simpler than discribed in the above comment.

**Comment by Cyan4973** [comment]
OK.
I agree on the objective : make it simpler to use, that's the real point.

I believe to have an idea for that, but need a bit more time to elaborate.

**Comment by luben** [comment]
I have done it on my side with a loop to consume all the parts of the frame header before entering the decompression loop.  I think it works OK and it is not more complex than before. I think the confusion came from the getFrameParams requiring to read the input but not consuming it.

**Comment by luben** [comment]
You can close this issue. I think it's resolved and was caused by my misunderstanding.

BTW, I noticed that the released version always puts a size header, even if invoking it with "cat file | zstd -c > file.zst". It can consume files with or without the size header though. It came out from my test that the Java bindings produce the same result as the zstd cli.

**Comment by Cyan4973** [comment]
I feel interested when an API behavior / usage is mis-understood.
That means it's unclear, and should be improved, for easier adoption.

So I'll keep your issue opened and try to find some ideas to improve this situation.

>  noticed that the released version always puts a size header, even if invoking it with "cat file | zstd -c > file.zst"

Interesting.
Indeed, it should not.
Maybe there is a little (harmless) bug which makes the system write a length (presumably `0`) even when none is available. If that is the case, this behavior should be improved, since it costs a few header bytes.

**Comment by luben** [comment]
Regarding the API, what about if the "ZSTD_getFrameParams" updates the context to not expect reading the frame header and the size (if available) again? It will be still API compatible with the current state.

**Comment by Cyan4973** [comment]
I expect the new streaming API to answer this topic as well.
Please re-open if it does not.
