### ISSUE TITLE
Ambiguous error handling

### ISSUE THREAD

**Issue by cher-nov** [Cyan4973/zstd#168]
I'm writing a wrapper for **ZStd** and faced with a problem.
AFAIK, currently in **ZStd** there's two ways to remember error code before it will be retrieved by user through some wrapper function:

1. Remember error code as last **_size_t_** for which **_ZSTD_isError()_** (**_ZBUFF_isError()_** in my case, but who cares?) has returned **_TRUE_**.
2. Convert errorneous **_size_t_** values to the **_ZSTD_ErrorCode_** enum value and store it.

The problem is this:

1. In first case, I can't preliminarily initialize error variable by some **_NO_ERROR_** value because **_size_t_** error codes are undocumented, could change in the future etc. Also I can't reset internal error state to **_NO_ERROR_** after the user has received an error code.
2. In second case, I can't write an interface function to get error description string properly because there's no version of **_ZSTD_getErrorName()_** for **_ZSTD_ErrorCode_** values.

I know that the possible solution is to store both **_size_t_** and **_ZSTD_ErrorCode_** values, but I'm sure that things could be done better from **ZStd** side.

Forgive me in advance for amazingly awful English.

**Comment by KrzysFR** [comment]
Are you using a language that supports exceptions? I've written a .NET wrapper, and I'm converting the errors into exceptions that are thrown back to the caller when they happen. This solves a lot of problems since now all my API return 'long' for sizes, or throw exception in case of errors (with the error code translated into text).

If your language does not have exceptions, but supports tuples or something equivalent, you could maybe return pairs of (bool, long) with (true, 1234) for success, and (false, error_code) for failure?

**Comment by cher-nov** [comment]
**KrzysFR**, all wrappers are written in Pure (?) C, and the interface is very simple.

**Comment by Cyan4973** [comment]
A few thoughts on reading your pretty good comments : 

- Between options 1 and 2, 2 looks the cleaner one
- There is no function yet to provide the error string from the enum => that's a show stopper. I shall create one.
- I'm considering changing ` ZSTD_getErrorName()` into ` ZSTD_getErrorString()`, because it used to be a single word (the stringification of the enum), but now it can be a complete sentence, so `Name` looks less logical.

>  I can't preliminarily initialize error variable by some NO_ERROR value because size_t error codes are undocumented, could change in the future etc.

- Indeed, they may change, but the value `0` is hard-coded to always mean "No error"

**Comment by cher-nov** [comment]
Completely agree.

> Indeed, they may change, but the value 0 is hard-coded to always mean "No error"

Yes, it is, and currently things are done by using my own definition of `ZSTD_NO_ERROR=0` for **_size_t_**. But in my opinion, it's not a good code style when I should make my own definitions for some third-party library.

**Comment by Cyan4973** [comment]
Trying to complete this issue in preparation of v0.6.1 :

If I do understand correctly, your need would be answered by a function like `ZSTD_getErrorName()` but using an `enum ZSTD_ErrorCode` as input parameter ?

**Comment by Cyan4973** [comment]
To be more precise, I'm considering the following API (to become part of `zstd_static.h`) : 

```
ZSTD_ErrorCode ZSTD_getErrorCode(size_t functionResult);
const char* ZSTD_getErrorString(ZSTD_ErrorCode code);
```

**Comment by KrzysFR** [comment]
Would the call to ZSTD_getErrorCode still be optional? Marshalling from managed languages to native has some cost so I would hope that this method could be replicated from the managed side and still be as simple as the current one.

For ZSTD_getErrorString this is less of an issue (only for exceptional cases and can be cached)

**Comment by Cyan4973** [comment]
> Would the call to ZSTD_getErrorCode still be optional? 

Yes.
`ZSTD_getErrorCode()` would be part of `zstd_static.h` for the foreseeable future, which is optional.

The usual error functions defined within `zstd.h` would remain available as-is : `ZSTD_isError()` and `ZSTD_getErrorName()`.

I feel the naming distinction between `ZSTD_getErrorName()` and `ZSTD_getErrorString()` is pretty poor, but on the other hand, I'm reluctant modifying functions already defined within `zstd.h`, as they are supposed to be stable.

**Comment by KrzysFR** [comment]
FYI, in my wrapper I do not call ZSTD_isError and simply replicate it into a static method that gets inlined by the .NET CLR, vs a virtual dispatch going through marshalling after every call.

Hopefully this will not change in the future :)

**Comment by Cyan4973** [comment]
Proposal uploaded into "dev" branch

**Comment by Cyan4973** [comment]
New method introduced within v0.6.1
