### ISSUE TITLE
midipix support / defines

### ISSUE THREAD

**Issue by kitt3n** [Cyan4973/zstd#181]
midipix ( http://midipix.org ) is an upcoming POSIX layer for windows, builds pretty much out of box with added defined(__midipix__) in two spots, also compresses and decompresses correctly \o/

`diff -ur zstd/programs/bench.c zstd.new/programs/bench.c
--- zstd/programs/bench.c	2016-05-07 21:45:23.964010000 +0200
+++ zstd.new/programs/bench.c	2016-05-05 16:24:24.547191263 +0200
@@ -53,7 +53,7 @@
 #include <time.h>        /* clock_t, nanosleep, clock, CLOCKS_PER_SEC */
 
 /* sleep : posix - windows - others */
-#if !defined(_WIN32) && (defined(__unix__) || defined(__unix) || (defined(__APPLE__) && defined(__MACH__)))
+#if !defined(_WIN32) && (defined(__unix__) || defined(__unix) || defined(__midipix__) || (defined(__APPLE__) && defined(__MACH__)))
 #  include <unistd.h>
 #  include <sys/resource.h> /* setpriority */
 #  define BMK_sleep(s) sleep(s)
@@ -70,7 +70,7 @@
 #  define SET_HIGH_PRIORITY /* disabled */
 #endif
 
-#if !defined(_WIN32) && (defined(__unix__) || defined(__unix) || (defined(__APPLE__) && defined(__MACH__)))
+#if !defined(_WIN32) && (defined(__unix__) || defined(__unix) || defined(__midipix__) || (defined(__APPLE__) && defined(__MACH__)))
    typedef clock_t BMK_time_t;
 #  define BMK_initTimer(ticksPerSecond) ticksPerSecond=0
 #  define BMK_getTime(x) x = clock()
`

**Comment by Cyan4973** [comment]
Good point @kitt3n ,
this is a fairly simple change, so let's support it.

**Comment by kitt3n** [comment]
Super! not sure why but the patch got changed from defined(__midipix__) to defined(__midipix)...

**Comment by Cyan4973** [comment]
Probably related to markdown formatting.
`__midipix__` becomes __midipix__ (bold character) if not enclosed in code quotes.

Also, given the project stated objective : 
> midipix is a development environment that lets you create programs for Windows using the standard C and POSIX APIs.

I'm surprised it doesn't work straight out of the box with just : 
`defined(__unix__) || defined(__unix)`

After all, the claim is : 

> If you are interested in cross-platform programming that reclaims the notion of write once, compile everywhere;

In which case, it shouldn't be necessary to modify the posix-compliant source code, not even to add a single new specific macro definition.

Do you have contacts with midipix development team ? Could they provide some hindsight to this point ?

**Comment by kitt3n** [comment]
Yeah, I am in #midipix on Freenode, he(midipix) hangs around there most of the time, also, he said the defines for windows should be:

`#ifdef _WIN32
//win32 code
#else
//portable code
#endif`

compared to how it is currently.. which would make it build out of box without define modifications for most unix-y platforms :p

**Comment by Cyan4973** [comment]
ok.
It's unclear what the better patch is then : adding `__midipix__`, as initially suggested, or change the order in which OS Macros are tested ?
The first suggestion seemed to produce less code modification.

Also, it would be good to have a way to test it, otherwise it will be a "blind" addition.

**Comment by Cyan4973** [comment]
Since adding a simple macro at a single place is a fairly benign change, I added `__midipix__` as suggested to the list of posix systems.

A few caveats : 
- It's untested ! we currently have no idea on how to add this target to CI environment
- I'm still puzzled why midipix doesn't simply define `__unix__`, which is much more common to check posix compliance.
- Even if it does not work, the worst thing that could happen is for `sleep` and `SET_HIGH_PRIORITY` to be useless, which wouldn't affect the program in any terrible way.

**Comment by midipix** [comment]
Two suggestions: one immediate, one more general, regarding the code in https://github.com/Cyan4973/zstd/blob/dev/lib/common/util.h#L66

* immediate suggestion: rewrite the block, applying the patter #if (known-non-portable-platform-A) {A-specific code} #else if (known-non-portable-platform-B) {B-specific code} # else {assume portable platform, portable code}

Using your current definitions of sleep(2), that would give you:

#  if defined(_WIN32)
#  include <windows.h>
#  define UTIL_sleep(s) Sleep(1000*s)
#  define UTIL_sleepMilli(milli) Sleep(milli)
#  define SET_HIGH_PRIORITY SetPriorityClass(GetCurrentProcess(), REALTIME_PRIORITY_CLASS)
# else
#  include <unistd.h>
#  include <sys/resource.h> /* setpriority */
#  define UTIL_sleep(s) sleep(s)
#  define UTIL_sleepMilli(milli) { struct timespec t; t.tv_sec=0; t.tv_nsec=milli*1000000ULL; nanosleep(&t, NULL); }
#  define SET_HIGH_PRIORITY setpriority(PRIO_PROCESS, 0, -20)
#  endif

--> three advantages of the above are that it 1) releases you from the need to keep track of all the portable systems out there, 2) allows your code to include newly added portable systems by default, rather than exclude them, and 3) makes supporting a newly added portable system a non-task (zero changes to your code).

* general suggestion: for as long as you support non-portable frameworks (i.e. WIN32), I'd suggest moving all of the #ifdef blocks into a designated header (say, config.h) rather than weaving them into multiple locations inside your project. That would not only keep your code proper cleaner, but also reduce the burden when you add/remove support for a non-portable platform.

**Comment by Cyan4973** [comment]
Windows isn't the only non-POSIX system out there.
`POSIX` cannot be "default".

Default must be "standard C", which offers much less functionalities.

In `utils.h`, "default" (`#else`) just disables calls to `sleep` and `SET_HIGH_PRIORITY`.
Once again, these functionalities are nice to have, but they bring nothing "essential".
Disabling them is not dramatic.

**Comment by midipix** [comment]
> Windows isn't the only non-POSIX system out there. <
That is true, and in your project you might be supporting several of them. And yet, there are only a few non-portable systems, and since supporting them requires a special action on your part, you already know who they are. The portable systems, on the other hand, are much more of a moving target, hence my suggestion to make the portable code path the default.

In any case, seems like this should be working one way or another, so all well.

**Comment by Cyan4973** [comment]
Supported in v0.6.1

**Comment by midipix** [comment]
Excellent, thanks! Am happy to help with testing.
