### ISSUE TITLE
[zstd-0.6.0] Decoding is a little slower than zlib on 32bit mobile system

### ISSUE THREAD

**Issue by powof2** [Cyan4973/zstd#190]
Hi and thanks for your great job,
tested on mobile OS, here are the test results : 

```
// File to compress : DroidSansFallback.ttf, 3.75 MB
compressed with zlib-lv6 : 1.747 MB
compressed with zstd-lv11 : 1.607 MB

// Excellent on iPhone 5s (64 bit system) (decoding)
zlib=71.34ms, zstd=26.89ms (best)
zlib=79.53ms, zstd=28.86ms (worst)

// Slower than zlib on iPad 2 (decoding, 32 bit system)
zlib=113.49ms, zstd=124.88ms (best)
zlib=133.93ms, zstd=148.68ms (worst)

// Slower than zlib on Android 4.4 (decoding, 32bit system)
zlib=81.93ms, zstd=87.61ms (best)
zlib=91.50ms, zstd=100.11ms (worst)
```

from above test results we can see that, on 32 bit systems, zstd is a little slower than zlib but not much, any chances to make zstd faster than zlib on old 32bit systems? thank you.

one more thing: i find that in debug mode zstd is also slower than zlib (in release mode zstd is faster) , here are the test results on win10 desktop, vs2013, win32 (not win64) : 

```
// debug version of zlib and zstd, decoding, win10 desktop, vs 2013, win32
zlib=60.55ms, zstd=136.25ms (best)
zlib=61.54ms, zstd=138.82ms (worst)
```

Thank you.

**Comment by Cyan4973** [comment]
Thanks for these metrics @powof2 .
We are in dire need of test systems and figures on mobile systems.

The fact that 32-bits system run slower is well known.
This is because zstd is built for 64-bits.
Some decoding operations can be done in a single pass in 64-bits, but require multiple steps in 32-bits.
This is due to register storage difference.

32-bits will always be slower than 64-bits, but maybe the difference can be reduced.
This, however, will require some attention, an optimization round specifically targeted at 32-bits.

**Comment by powof2** [comment]
Thanks for your reply.

It would be great if the difference can be reduced (as long as it has no bad influence on 64-bits zstd) since 32-bits devices and desktops are still live out there. 
```
// some devices that 32-bits only
iPhones before iPhone 5s
iPads before iPad Air
iPad minis before iPad mini Retina
All Android devices before Android 5.0 (Android Lollipop)
```
So far I'm very satisfied with the result on iPhone 5s, as for the old devices, I think i can live with that since the difference is not that much.
