### ISSUE TITLE
wrong decompressed output

### ISSUE THREAD

**Issue by doublex** [Cyan4973/zstd#242]
Hello,
I have tried you new zstd streaming API. The decompressed data is not equal to the source.
A small testcase is attached.
Steps to reproduce:
````
gcc -o zstd-test zstd-test.c -I/tmp/zstd/lib/common /tmp/zstd/lib/common/entropy_common.c /tmp/zstd/lib/common/fse_decompress.c /tmp/zstd/lib/common/zstd_common.c /tmp/zstd/lib/common/xxhash.c /tmp/zstd/lib/compress/fse_compress.c /tmp/zstd/lib/compress/huf_compress.c /tmp/zstd/lib/compress/zstd_compress.c /tmp/zstd/lib/decompress/huf_decompress.c /tmp/zstd/lib/decompress/zstd_decompress.c
./zstd-test
diff /tmp/source.txt /tmp/decompressed.txt
````
Thanks a lot
Marcus

[zstd-test.txt](https://github.com/Cyan4973/zstd/files/355041/zstd-test.txt)

**Comment by Cyan4973** [comment]
On the decompression side,
your `output_buffer` policy doesn't respect the same "contiguity" as the source on the compression side.

Decoding fails because data is decoded into the same buffer as the one used previously for previous block, overwriting previous block in the process. Any back-reference > 128 KB will catch the new data instead of the old one, generating corruption.

Prefer decompressing directly into `target` buffer, so that block lays next to each other.

Alternatively, you may try `zbuff.h` API, which is robust a streaming interface, allowing your implementation to do whatever it wishes with input/output buffers. It would have passed this test for example.

**Comment by doublex** [comment]
Thanks - sorry for disturbing
