### ISSUE TITLE
Coverity identifies possible issues in zstd

### ISSUE THREAD

**Issue by nemequ** [Cyan4973/zstd#246]
Coverity identifies several issues in current zstd; see https://scan.coverity.com/projects/squash

One of the issues is that potential leak I filed an issue about last week, which is already fixed.  Another is about [falling through a switch](http://security.coverity.com/blog/2013/Sep/gimme-a-break.html), which is probably intentional, but the others (which are all out-of-bounds reads) seem like they could be legit.

I sent you an invitation so you can view the issues through the squash project, but you might want to consider creating a project for zstd; Coverity is a great tool.  There can be some false positives to wade through, but it also catches a lot of real issues… definitely worth it, IMHO.

**Comment by Cyan4973** [comment]
Thanks for the hint @nemequ .
Indeed, I've been using coverity for [lz4](http://www.lz4.org) development, though it's unfortunately not as automated as the rest of the test suite, since a special branch must be created and updated for it.

For zstd however, I'm a bit puzzled.
Last time I tried coverity, the number of false positives were too high, and not always solvable.
With little way how turning them off without making the code "coverity specific", I finally gave up.

This was many months ago, so maybe things have changed for the better since, and it could be tested again.

**Comment by Cyan4973** [comment]
I've set up a [branch for coverity_scan](https://github.com/Cyan4973/zstd/tree/coverity_scan).
The interface seems to allow flagging false positives.
If it works as expected (that is, false positivez are then automatically excluded from the list of warnings), then it will be possible to use this test without remaining "ghosts",
making the tool quite useful.
So let's start using it ...

**Comment by kklouzal** [comment]
Checking up on ZStd I was sad to see the coverity scan has not been ran in almost a years time! I suggest adding the CoverityScan badge to the main page and automating builds from the main branch in TravisCI. The frequency in which Travis runs is within the bounds of what Coverity allows and if you happen to go over they will simply reject new scans until the next day.

**Comment by Cyan4973** [comment]
Sorry, the project is simply no longer allowed to use coverity.

**Comment by ryao** [comment]
@Cyan4973 Are you at liberty to say why? I thought Coverity was available to all OSS projects.

**Comment by Cyan4973** [comment]
Something like an perceived microscopic legal risk. Most likely blown out of proportion, but just say "wolf".
