### ISSUE TITLE
dictionary compression example not matching zstd output

### ISSUE THREAD

**Issue by jrmarino** [Cyan4973/zstd#275]
Hi Yann, I've noticed something interesting.

given: a dictionary generated with zstd --train

if I compress files using a program generated by the dictionary compression example:

1. The resulting compressed files are 5 bytes smaller than those generated by zstd with the same dictionary
2. zstd can uncompress these compressed files (as expected)
3. the dictionary-decompress example program cannot decompressed them (the get decompressed size returns 0 and fails)

conversely, the dictionary-decompress program can decompress the files compressed by zstd so that appears to generally work.

It appears zstd is doing something more (something that would account for these 5 extra bytes).

I discovered this testing the Ada bindings and confirmed the same thing happens on the C examples.

you might be able to reproduce using the same dictionary:
https://github.com/jrmarino/zstd-ada/tree/master/examples/testdata

**Comment by Cyan4973** [comment]
Indeed, you are right.

By default, `zstd` does the following 2 things which the demo does not : 
- provide the original file size into header (+2 bytes)
- add a checksum to check result validity (+4 bytes)

Because the demo does not provide a file size, it does provide a window size instead (-1 byte).
Hence 5 bytes of difference.

In my view, problem is, demo should provide original size into header.
But that's not necessarily the fault of the "demo" itself, since it uses basic functions.
It should be up to the said basic functions to take care of it automatically.

So now that's something to investigate ....

**Comment by Cyan4973** [comment]
Dictionary compression examples and library default behavior fixed in "dev" branch.
Also added a dictionary compression test in `examples/Makefile`

**Comment by Cyan4973** [comment]
fixed in v0.8.1
