### ISSUE TITLE
Compressing 4x256K buffers smaller than compressing 1x1M

### ISSUE THREAD

**Issue by hashbackup** [Cyan4973/zstd#277]
I'm doing some zstd testing with HashBackup and ran into something unexpected.  The data file is a 1GB VM image, so all kinds of data on it.  

For this test file, zstd compress at level 1 using 256K buffers compresses better than using 1MB buffers.  Here is the tail of the test output:
```
#616 offset 1056964608: 256K comp 714757 < 1M comp 714928; 256K tot 372580950, 1M tot 373733064
#617 offset 1063256064: 256K comp 354649 < 1M comp 355409; 256K tot 374340369, 1M tot 375491021
#618 offset 1064304640: 256K comp 635069 < 1M comp 635149; 256K tot 374975438, 1M tot 376126170
#619 offset 1066401792: 256K comp 472852 < 1M comp 472885; 256K tot 376071665, 1M tot 377222401
```
This means there were 619 times where using a 1MB buffer compressed worse than 4x256K buffers.  The difference for the whole file is shown on the last line.

With lz4 on the same file, it compresses better with 1MB buffers than with 256K buffers.  There are only 31 instances of 4x256K compressing better than a single 1M buffer:
```
#29 offset 898629632: 256K comp 260036 < 1M comp 260218; 256K tot 442865490, 1M tot 441529374
#30 offset 900726784: 256K comp 366970 < 1M comp 368881; 256K tot 443453702, 1M tot 442116888
#31 offset 1001390080: 256K comp 429181 < 1M comp 429218; 256K tot 468588404, 1M tot 466839992
```
Is this expected behavior?

**Comment by Cyan4973** [comment]
Hi @hashbackup 

It's certainly not an "expected" result, but it is indeed possible.

Reason is : 
"fast" mode uses a cheap heuristic, which tries to select "good matches".
It doesn't guarantee it found the best ones.
In particular, its bet is "static", and since each file is different, the bet will be more or less correct.

Your use case seems unfavorable.
Not sure why, as it can be a combination of local conditions.

**Comment by hashbackup** [comment]
What surprised me is that lz4 didn't have similar behavior.  lz4 only has this behavior 3% of the time, but zstd -1 has it 67% of the time (for this file).

It also is not just one section of the VM image, but seems evenly distributed throughout the image (it's a Ubuntu VM image - nothing special).

One theory I had is that lz4 might compress in 64K or 128K groups.  If one group doesn't compress well, it doesn't affect the other groups much.  But if zstd gets halfway through a 1MB buffer and decides it isn't compressing well, it might abandon the other 512K whereas lz4 might still try to compress it (and be successful).  I haven't studied the lz4 or zstd code, so this is just a wild guess.

**Comment by Cyan4973** [comment]
`lz4` has less of an issue with "bad" guesses, because offset always cost the same (2 bytes).

In contrast, offset costs for `zstd` are variable. So finding a match at long distance costs more than short distance. Hence more "long distance" matches is not always better. Plus it has a capability to "follow structures", with repcodes. But that only works as long as surrounding matches remain within the tracked structure. So a long-distance match outside of the structure will break the pattern.

Anyway, to limit such side-effect, `zstd -1` has an internal limit, at 512 KB.
It's generally a good enough limit.
But maybe in some cases, it would be beneficial to be shorter, such as 256 KB in your example.

**Comment by hashbackup** [comment]
My percentage calculation was off a bit: 619/1024 = 60.45% of the time a 1M buffer compressed worse than 4x256K.

I tried the same test using a 512K buffer instead of 1M, thinking there would be fewer "bad" guesses.  But 1363/2048 = 66.55% of the 512K compressions were bigger than 256K compressions, so it's worse.

It's not a big problem: with 256K buffers it compresses the file to 35.17% of original, with 512K it is 35.52%, with 1M it's 35.28.  It just seems unusual behavior.
