### ISSUE TITLE
Log messages in "--train" mode of zstd CLI outputs incorrect size for input file.

### ISSUE THREAD

**Issue by david-y-lam** [Cyan4973/zstd#292]
Note that for a 1.0 GiB file, it says `sorting 1 files of total size 0 MB ...`. Full logs below.

```
davidlam-mbp:zstd davidlam$ du -sh myfile
1.0G    myfile
davidlam-mbp:zstd davidlam$ ./zstd --train ./myfile
!  Warning : nb of samples too low for proper processing
!  Please provide one file per sample
!  Avoid concatenating multiple samples into a single file
!  otherwise, dictBuilder will be unable to find the beginning of each sample
!  resulting in distorted statistics
sorting 1 files of total size 0 MB ...
finding patterns ...
!  warning : created dictionary significantly smaller than requested (0 < 112640)
!  consider increasing the number of samples (total size : 0 MB)
statistics ...
warning : could not compress sample size 131072
HUF_writeCTable errorSave dictionary of size 7 into file dictionary
```

From what I can tell in the code, we limit samples files to the first 128 KiB (https://github.com/Cyan4973/zstd/blob/master/programs/dibio.c#L113). Another note is that because of that 128 KiB limit, we will never output for a single file anything other than `0 MB`. Should this log message be updated?

**Comment by Cyan4973** [comment]
This one is a difficult issue.

`zstd --train` expects a serie of individual messages,
not a big concatenated version of them.

This is important, as it cannot guess where messages start within a big concatenated file.

Therefore, a single big 1 GB file for training is a bad idea.
The warning messages try to explain that. Apparently, it's not clear enough.

I'm also worried that this situation, providing the dictBuilder with a single big concatenated file, seems to happen very often. So users feel it's natural to provide it this way.
Not sure about what to do, how to educate, are there better possibilities, etc.

**Comment by david-y-lam** [comment]
> Therefore, a single big 1 GB file for training is a bad idea.
> The warning tries to explain that. Apparently, it's not clear enough. 

The warnings you mention is unrelated to the issue of the incorrect size in the log message though right?

**Comment by Cyan4973** [comment]
It is.
Though it seems not clear enough.

When provided with a single sample, the dictionary builder will consider that, beyond 128 KB, dictionary will no provide any benefit. So it will stop analyzing the sample beyond that limit.

So it doesn't matter if the sample is 129KB, or 1MB, or 1GB, the builder will only take in consideration its first 128 KB.

That's because it believes the file is a single sample,
as opposed to a concatenation of multiple samples inside a single file.

**Comment by david-y-lam** [comment]
thanks for explanation, so would the fix be to add a warning log message in https://github.com/Cyan4973/zstd/blob/master/programs/dibio.c#L102-L104, and change https://github.com/Cyan4973/zstd/blob/master/lib/dictBuilder/zdict.c#L515 to use KiB instead of MiB? I can send a pull request if so.

**Comment by Cyan4973** [comment]
> so would the fix be to add a warning log message whenever size is greater than 128 KiB

That would be too much.
There are valid cases where, among a serie of messages used as sample set, some of them are > 128 KB. In which case, it's valid to use only the first 128 KB to populate the sample set.

The real indicator is the number of samples.
A single file means a single sample, which is clearly too little to create a dictionary from.
Even 2 or 3 samples is really too low to build anything meaningful.

The current code generates a warning message as soon as `nbSamples < 5` : 
https://github.com/Cyan4973/zstd/blob/master/programs/dibio.c#L206

The main situation to avoid is the one you met, when all samples are provided concatenated into a single file. Main objective is to provide a clear warning message which explain users how the training mode is supposed to work (aka, one file per sample).

A more complex complementary solution could be to provide a way to split the big file into individual samples. I'm afraid it will introduce syntax complexities though, and there is no "universal" solution. Simply concatenating individual messages into a big file is bound to fail due to potential absence of a clean end / begin signal. It means the concatenating process is not trivial and will be impacted too. At which stage, it's questionable what are the gains compared to providing the samples as individual files.

**Comment by Cyan4973** [comment]
I've changed a bit the text and behavior in case of dictionary building failure.
Hopefully, the new version (dev branch) helps clarity.

**Comment by david-y-lam** [comment]
cool, thanks for your work!
