### ISSUE TITLE
new compression google/brotli

### ISSUE THREAD

**Issue by tomByrer** [Cyan4973/zstd#35]
https://github.com/google/brotli
Would be nice to see on your performance test chart.  Perhaps you guys can learn from each other?

**Comment by Cyan4973** [comment]
Thanks @tomByrer 

Yes, I'm aware of the Brotli project by Google.
I believe it's a nice team making a really good job.

However, the direction selected is quite different from Zstd, resulting in fairly different optimization directions.
If I'm not mistaken,
initially, Brotli was about speed, most importantly decompression speed, and targeting a specific file type, fonts. They have since changed course a bit, by now targeting "general-purpose compression" and "more compression", but these roots are still there.

I believe that they made the following calculation : speed => huffman => poor compression at high statistics => Let's make statistics small => Lots of symbols (2nd order). In selecting which symbols to add, the initial use case (font compression) was rather key to determine them. They are now statically defined in the format.
Zstd rather made the following choice : speed => fse => good compression at high statistics => Let's use less symbols. And I haven't really finished this part of the job, but that gives you a direction.

So of course, since both algorithms are LZ-based, they still have some common elements, but due to these different initial impulsions, there are also some important design differences, which can't be erased by a last minute addition (such as swapping fse and huffman).

Also, note that fse did not existed when brotli started, so it limited their choice.

**Comment by tomByrer** [comment]
Yes, I suspected it was meant to replace Zopfli for WOFF/WOFF2; thanks for the details!
