### ISSUE TITLE
zstd reads outside buffer for short inputs

### ISSUE THREAD

**Issue by nemequ** [Cyan4973/zstd#73]
When provided with a short input (in this case, a single byte), zstd will read outside of the input buffer.  Here is a log from the single-byte test run under AddressSanitizer:

https://travis-ci.org/quixdb/squash/jobs/91010226#L3636

**Comment by Cyan4973** [comment]
Thanks for notification Evan, I'll look into it

**Comment by Cyan4973** [comment]
Thanks @nemequ,
the bug has been fixed within _newAPI_ branch, which will become v0.4 in the future.

The fix is simple enough (don't compress small block sizes, it's useless anyway due to header sizes). more complex, the fuzzer test suite has been updated to produce and detect such cases. It slows it down a bit, but make its coverage more complete.

I don't recommend using the "newAPI" branch right now, since it's in construction, so this fix will be present into v0.4.
